### PR TITLE
Add instructions for temporary demo env

### PR DESCRIPTION
**Pull request by kklin**
Hi @cleancoderocker, @ejj reached out a couple weeks about building a way to spin up demo envs for Streamsheets. We've finished the first version!

Screen Shot 2020-09-13 at 3 52 09 PM

The demo env works great for me -- I was able to fully complete the dogs & cats example in the getting started.

What do you think? Does it still seem useful?

### CODE REVIEW

**Comment by kklin** [comment]
Hmm looks like there are some websockets errors that I need to look into, so the stream machines page isn't loading.

In the meantime, do you have any feedback on the UX? Here's a small demo that works: https://kelda.io/preview-env/?repo=https://github.com/kelda/node-todo.git&service=web&port=8080

**Comment by kklin** [comment]
Ok, streamsheets is working now! [Check it out here](https://kelda.io/preview-env/?repo=https://github.com/cedalo/streamsheets.git&composeFiles=deployment/standard/installer/services/docker-compose/docker-compose.prod.yml&service=reverseproxy&port=8081&env=VERSION=1.4)

**Comment by cleancoderocker** [comment]
Hi @kklin, 

thanks for your pull request! We will have a look at it and get back to you as soon as possible.

Cheers,
Philip

**Comment by kklin** [comment]
Thanks @cleancoderocker!

**Comment by kklin** [comment]
Hi @cleancoderocker, any thoughts?

**Comment by cleancoderocker** [comment]
Hi @kklin,

thanks for trying out Streamsheets with your hosting service! We would be very happy if you included Streamsheets in your hosting offer (preferably in the current version 2.1  😊, which is much easier to set up thanks to the single Docker image). 

However, after consulting with our marketing team, we came to the conclusion that we will not integrate any buttons for external service providers on our GitHub page. 

Of course it would be nice if we could keep in touch.

thanks again and best regards,
Philip

**Comment by kklin** [comment]
Thanks for taking the time to try it out! Let's definitely keep in touch.

**Pull request closed without merging**
